env:
  browser: true
  commonjs: true
  es2021: true
  jest: true

extends:
  - airbnb-base
  - prettier
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: latest

rules:
  import/no-dynamic-require: off
  global-require: off
  array-callback-return: off
  no-param-reassign: off

plugins:
  - jest
