services:
  db:
    image: postgres:13
    container_name: petstore-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: petstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: petstore-backend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  
  frontend:
    build: ./frontend
    container_name: petstore-frontend
    env_file: ./frontend/.env
    ports:
      - "8080:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
